In [9]:
import numpy as np
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = a%2 == 1
print(a[b])

[1 3 5 7 9]


In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

In [21]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
b = np.where((a>=5)&(a<=10))
a[b]

array([ 6,  9, 10])

In [57]:
a = np.arange(9).reshape(3,3)
a = a[:,[1,0,2]]#swap columns
a

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [56]:
a = np.arange(9).reshape(3,3)
a = a[[1,0,2],:]#swap rows
a

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [58]:
a = np.arange(9).reshape(3,3)
a = a[:,[2,1,0]]#reverse columns
#a = a[:,::-1] also reverse columns
a

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])